{
 "title": "stree_bk",
 "tags": [
  "stree",
  "hawkeye"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prome-server" },
   {
    "name": "group",
    "query": "label_values(gpa_all_num_count,gpa_name)"
   },
   {
    "name": "resource_type",
    "query": "label_values(resouce_num_count,resource_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "资源总数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "resouce_num_count>0", "legendFormat": "{{resource_type}}" }
     ]
    },
    {
     "title": "ecs总数按云厂商分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_cloud_provider_count{resource_type=\"ecs\"}",
       "legendFormat": "{{resource_type}} {{cloud_provider}}"
      }
     ]
    },
    {
     "title": "elb总数按云厂商分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_cloud_provider_count{resource_type=\"elb\"}",
       "legendFormat": "{{resource_type}} {{cloud_provider}}"
      }
     ]
    },
    {
     "title": "rds总数按云厂商分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_cloud_provider_count{resource_type=\"rds\"}",
       "legendFormat": "{{resource_type}} {{cloud_provider}}"
      }
     ]
    },
    {
     "title": "dcs总数按云厂商分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_cloud_provider_count{resource_type=\"dcs\"}",
       "legendFormat": "{{resource_type}} {{cloud_provider}}"
      }
     ]
    },
    {
     "title": "ecs总数按region分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_region_count{resource_type=\"ecs\"}",
       "legendFormat": "{{resource_type}} {{region}}"
      }
     ]
    },
    {
     "title": "elb总数按region分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_region_count{resource_type=\"elb\"}",
       "legendFormat": "{{resource_type}} {{region}}"
      }
     ]
    },
    {
     "title": "rds总数按region分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_region_count{resource_type=\"rds\"}",
       "legendFormat": "{{resource_type}} {{region}}"
      }
     ]
    },
    {
     "title": "dcs总数按region分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "resouce_num_region_count{resource_type=\"dcs\"}",
       "legendFormat": "{{resource_type}} {{region}}"
      }
     ]
    }
   ]
  },
  { "title": "服务树GPA资源统计-ECS/ELB/RDS/DCS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "gpa:${group} ${resource_type} 数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gpa_all_num_count{gpa_name=~\"$group.*\",resource_type=\"$resource_type\"}",
     "legendFormat": "{{gpa_name}}"
    }
   ]
  },
  {
   "title": "gpa: ${group} ${resource_type} 云厂商分布",
   "type": "graph",
   "description": "根据套餐算出的",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpa_all_cloud_provider_num_count{gpa_name=~\"$group.*\",resource_type=\"$resource_type\"}",
     "legendFormat": "{{cloud_provider}}  : {{gpa_name}} "
    }
   ]
  },
  {
   "title": "gpa : ${group} ${resource_type}  Region分布",
   "type": "graph",
   "description": "根据套餐算出的",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpa_all_region_num_count{gpa_name=~\"$group.*\",resource_type=\"$resource_type\"}",
     "legendFormat": "{{gpa_name}}  - {{region}}  "
    }
   ]
  },
  {
   "title": "gpa : ${group} ${resource_type} 集群分布",
   "type": "graph",
   "description": "根据套餐算出的",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpa_all_cluster_num_count{gpa_name=~\"$group.*\",resource_type=\"$resource_type\"}",
     "legendFormat": "{{gpa_name}}  - {{cluster}}  "
    }
   ]
  },
  {
   "title": "gpa :${group} ecs实例规格分布",
   "type": "graph",
   "description": "根据套餐算出的",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gpa_ecs_instance_type_num_count{gpa_name=~\"$group.*\"}",
     "legendFormat": "{{gpa_name}}  :  {{instance_type}} {{cpu_mem}} "
    }
   ]
  },
  {
   "title": "gpa :${group} cpu核数",
   "type": "graph",
   "description": "根据套餐算出的",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gpa_cpu_cores{gpa_name=~\"$group.*\"}",
     "legendFormat": "{{gpa_name}}"
    }
   ]
  },
  {
   "title": "gpa :${group} 内存总大小(单位GB)",
   "type": "graph",
   "description": "根据套餐算出的",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "gpa_mem_gbs{gpa_name=~\"$group.*\"}",
     "legendFormat": "{{gpa_name}}"
    }
   ]
  }
 ]
}